import type { Metadata } from "next";
import React from "react";
import { JetBrains_Mono } from "next/font/google";
import "../styles/globals.css";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer/footer";

const jetBrainsMono = JetBrains_Mono({ 
    subsets: ["latin"], 
    weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
    variable: '--font-jetbrainsMono' 
});

export const metadata: Metadata = {
  title: "SantatraDEV",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={jetBrainsMono.variable}>
            <Header />
            {children}
            <Footer />
        </body>
        </html>
    );
}
